/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bookcab;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kriz
 */
public class Menu_Driver extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Driver
     */
    public Menu_Driver() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_exit.setBorder(label_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cabIcon = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        jLabel_mini = new javax.swing.JLabel();
        jLabel_exit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfPhone = new javax.swing.JTextField();
        jlName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jlAdd = new javax.swing.JLabel();
        tfAdd = new javax.swing.JTextField();
        jlPhone = new javax.swing.JLabel();
        jluserIcon = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        tfID = new javax.swing.JTextField();
        jlName2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlDelete = new javax.swing.JLabel();
        jlPlate = new javax.swing.JLabel();
        tfPlate = new javax.swing.JTextField();
        jlBrand = new javax.swing.JLabel();
        tfBrand = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        cabIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kriz\\OneDrive - umindanao.edu.ph\\Documents\\IconProject\\cab.png")); // NOI18N

        lbTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 51, 51));
        lbTitle.setText("BooK");

        jLabel_mini.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_mini.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_mini.setText(" -");
        jLabel_mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseExited(evt);
            }
        });

        jLabel_exit.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_exit.setText(" x");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cabIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel_mini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_exit, jLabel_mini});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_mini)
                            .addComponent(jLabel_exit)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cabIcon)
                            .addComponent(lbTitle))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tfPhone.setEditable(false);
        tfPhone.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPhoneFocusLost(evt);
            }
        });
        tfPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPhoneKeyTyped(evt);
            }
        });

        jlName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlName.setText("Full name");

        tfName.setEditable(false);
        tfName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNameFocusLost(evt);
            }
        });
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        jlAdd.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlAdd.setText("Address");

        tfAdd.setEditable(false);
        tfAdd.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAddFocusLost(evt);
            }
        });

        jlPhone.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlPhone.setText("Phone #");

        jluserIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kriz\\OneDrive - umindanao.edu.ph\\Documents\\IconProject\\user (2).png")); // NOI18N

        btnEdit.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(204, 102, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 102, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSignOut.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        tfID.setEditable(false);
        tfID.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfIDFocusLost(evt);
            }
        });
        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        jlName2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlName2.setText("ID");

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 0));
        jLabel4.setText("Your Info");

        jlDelete.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlDelete.setText("Delete Account?");
        jlDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlDeleteMouseExited(evt);
            }
        });

        jlPlate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlPlate.setText("Plate Number");

        tfPlate.setEditable(false);
        tfPlate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfPlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPlateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPlateFocusLost(evt);
            }
        });

        jlBrand.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlBrand.setText("Brand");

        tfBrand.setEditable(false);
        tfBrand.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfBrand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBrandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBrandFocusLost(evt);
            }
        });
        tfBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBrandKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlName2)
                            .addComponent(jlAdd)
                            .addComponent(jlName)
                            .addComponent(tfAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(tfName)
                            .addComponent(tfID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlPlate)
                            .addComponent(jlBrand)
                            .addComponent(tfPlate, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(tfBrand)
                            .addComponent(jlPhone)
                            .addComponent(tfPhone)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jluserIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jlDelete))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(97, 97, 97)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jluserIcon)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jlName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jlPlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignOut)
                .addGap(18, 18, 18)
                .addComponent(jlDelete)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneFocusGained

        jlPhone.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfPhoneFocusGained

    private void tfPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneFocusLost

        jlPhone.setForeground(Color.black);
    }//GEN-LAST:event_tfPhoneFocusLost

    private void tfPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPhoneKeyTyped
        //number only

        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tfPhoneKeyTyped

    private void tfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusGained

        jlName.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfNameFocusGained

    private void tfNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusLost

        jlName.setForeground(Color.black);
    }//GEN-LAST:event_tfNameFocusLost

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed

    }//GEN-LAST:event_tfNameActionPerformed

    private void tfAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddFocusGained

        jlAdd.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfAddFocusGained

    private void tfAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddFocusLost

        jlAdd.setForeground(Color.black);
    }//GEN-LAST:event_tfAddFocusLost

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        tfName.setEditable(true);
        tfAdd.setEditable(true);
        tfPhone.setEditable(true);
        tfPlate.setEditable(true);
        tfBrand.setEditable(true);

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if(JOptionPane.showConfirmDialog(null, "Confirm Save", "Update", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) { 
            
        String fname = tfName.getText();
        String address = tfAdd.getText();
        String phone = tfPhone.getText();
        String id = tfID.getText();
        String plate = tfPlate.getText();
        String brand = tfBrand.getText();

        if(verifyFields()) {

            PreparedStatement ps;
            ResultSet rs;
            String registerUserQuery = "UPDATE `driver` SET `full_name` = ?, `address` = ?, `phone` = ?, `plateNumber` = ?, `carType` = ? WHERE `id` = ?";

            try {
                ps = MyConnect.getConnection().prepareStatement(registerUserQuery);
                ps.setString(1, fname);
                ps.setString(2, address);
                ps.setString(3, phone);
                ps.setString(4, plate);
                ps.setString(5, brand);
                ps.setString(6, id);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Your Driver Account Has been Updated");
            } catch (SQLException ex) {
                Logger.getLogger(registerBooker.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        tfName.setEditable(false);
        tfAdd.setEditable(false);
        tfPhone.setEditable(false);
        tfPlate.setEditable(false);
        tfBrand.setEditable(false);
        
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed

        if(JOptionPane.showConfirmDialog(null, "Confirm to Sign Out", "Sign Out", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            UserLogin u = new UserLogin();
            u.setVisible(true);
            u.pack();
            u.setLocationRelativeTo(null);

            this.dispose();
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void tfIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDFocusGained

    private void tfIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDFocusLost

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed

    private void jlDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDeleteMouseClicked

        String id = tfID.getText();

        if(JOptionPane.showConfirmDialog(null, "Confirm to Delete", "Delete Account", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            try {
                PreparedStatement ps = MyConnect.getConnection().prepareStatement("DELETE FROM `driver` WHERE `id` = ?");
                ps.setString(1, id);

                int k = ps.executeUpdate();

                if(k==1){
                    JOptionPane.showMessageDialog(null, "Your Driver Account Has been Deleted");
                    this.dispose();
                    UserLogin l = new UserLogin();
                    l.setVisible(true);
                    l.pack();
                    l.setLocationRelativeTo(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Your Record Failed to Delete");
                }

            } catch (SQLException ex) {
                Logger.getLogger(registerBooker.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jlDeleteMouseClicked

    private void jlDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDeleteMouseEntered

        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204,102,0));
        jlDelete.setBorder(label_border);
        jlDelete.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_jlDeleteMouseEntered

    private void jlDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDeleteMouseExited

        jlDelete.setBorder(null);
        jlDelete.setForeground(Color.black);
    }//GEN-LAST:event_jlDeleteMouseExited

    private void tfPlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPlateFocusGained
        
        jlPlate.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfPlateFocusGained

    private void tfPlateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPlateFocusLost
        jlPlate.setForeground(Color.black);
    }//GEN-LAST:event_tfPlateFocusLost

    private void tfBrandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBrandFocusGained
        jlBrand.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfBrandFocusGained

    private void tfBrandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBrandFocusLost
       jlBrand.setForeground(Color.black);
    }//GEN-LAST:event_tfBrandFocusLost

    private void tfBrandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBrandKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBrandKeyTyped

    private void jLabel_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_miniMouseClicked

    private void jLabel_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_miniMouseEntered

    private void jLabel_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_miniMouseExited

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jLabel_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_exitMouseEntered

    private void jLabel_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_exitMouseExited

    public boolean verifyFields() {
        
        String fname = tfName.getText();
        String phone = tfPhone.getText();
        String address = tfAdd.getText();
        
        //check empty fields
        if (fname.trim().equals("") || address.trim().equals("") || phone.trim().equals("")) {
            
            JOptionPane.showMessageDialog(null, "One or More Fields Are Empty", "Empty Fields", 2);
            return  false;
        }
        
        //succesfull
        else {
            return true;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Driver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JLabel cabIcon;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_mini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlAdd;
    private javax.swing.JLabel jlBrand;
    private javax.swing.JLabel jlDelete;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlName2;
    private javax.swing.JLabel jlPhone;
    private javax.swing.JLabel jlPlate;
    private javax.swing.JLabel jluserIcon;
    private javax.swing.JLabel lbTitle;
    public static javax.swing.JTextField tfAdd;
    public static javax.swing.JTextField tfBrand;
    public static javax.swing.JTextField tfID;
    public static javax.swing.JTextField tfName;
    public static javax.swing.JTextField tfPhone;
    public static javax.swing.JTextField tfPlate;
    // End of variables declaration//GEN-END:variables
}
