/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bookcab;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kriz
 */
public class Menu_Booker extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Booker
     */
    public Menu_Booker() {
        initComponents();
        showDriver();
        
        this.setLocationRelativeTo(null);
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_exit.setBorder(label_border);
    }
    
    public ArrayList<User> userList() {
        ArrayList<User> userList = new ArrayList<>();
        
        PreparedStatement ps;
        ResultSet rs;
        String DriverQuery = "SELECT * FROM `driver`";
        
    
        try {
            
            //ps = MyConnect.getConnection().prepareStatement(DriverQuery);
            Statement st = MyConnect.getConnection().createStatement();
            rs = st.executeQuery(DriverQuery);
            User user;
            
            while(rs.next()) {
                user = new User(rs.getString("full_name"), rs.getString("address"), rs.getString("phone"), rs.getString("gender"), rs.getString("plateNumber"), rs.getString("carType"));
                userList.add(user);
            }
            
        } catch (SQLException ex) {
        Logger.getLogger(registerBooker.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userList;       
    }
    
    public void showDriver() {
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)tableDriver.getModel();
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++) {
        
            row[0]=list.get(i).getfname();
            row[1]=list.get(i).getadd();
            row[2]=list.get(i).getphone();
            row[3]=list.get(i).getgender();
            row[4]=list.get(i).getpltNum();
            row[5]=list.get(i).getbrand();
            model.addRow(row);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cabIcon = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfPhone = new javax.swing.JTextField();
        jlName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jlAdd = new javax.swing.JLabel();
        tfAdd = new javax.swing.JTextField();
        jlPhone = new javax.swing.JLabel();
        jluserIcon = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        tfID = new javax.swing.JTextField();
        jlName2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlDelete = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_mini = new javax.swing.JLabel();
        jLabel_exit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDriver = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jlName1 = new javax.swing.JLabel();
        tfNameD = new javax.swing.JTextField();
        jlAdd1 = new javax.swing.JLabel();
        tfAddD = new javax.swing.JTextField();
        jlPhone1 = new javax.swing.JLabel();
        tfPhoneD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlPlate = new javax.swing.JLabel();
        tfPlate = new javax.swing.JTextField();
        tfBrand = new javax.swing.JTextField();
        jlBrand = new javax.swing.JLabel();
        jlGender = new javax.swing.JLabel();
        tfGender = new javax.swing.JTextField();
        btnProceed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        cabIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kriz\\OneDrive - umindanao.edu.ph\\Documents\\IconProject\\cab.png")); // NOI18N

        lbTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 51, 51));
        lbTitle.setText("BooK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cabIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cabIcon)
                    .addComponent(lbTitle))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tfPhone.setEditable(false);
        tfPhone.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPhoneFocusLost(evt);
            }
        });
        tfPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPhoneKeyTyped(evt);
            }
        });

        jlName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlName.setText("Full name");

        tfName.setEditable(false);
        tfName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNameFocusLost(evt);
            }
        });
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        jlAdd.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlAdd.setText("Address");

        tfAdd.setEditable(false);
        tfAdd.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAddFocusLost(evt);
            }
        });

        jlPhone.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlPhone.setText("Phone #");

        jluserIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kriz\\OneDrive - umindanao.edu.ph\\Documents\\IconProject\\user (2).png")); // NOI18N

        btnEdit.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(204, 102, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 102, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSignOut.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        tfID.setEditable(false);
        tfID.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfIDFocusLost(evt);
            }
        });
        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        jlName2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlName2.setText("ID");

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 0));
        jLabel4.setText("Your Info");

        jlDelete.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlDelete.setText("Delete Account?");
        jlDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlDeleteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlName2)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jlAdd)
                                .addComponent(jlPhone)
                                .addComponent(jlName)
                                .addComponent(tfAdd)
                                .addComponent(tfPhone)
                                .addComponent(tfName)
                                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jluserIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jlDelete)
                        .addGap(38, 38, 38)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jluserIcon)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addComponent(btnSignOut)
                .addGap(18, 18, 18)
                .addComponent(jlDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_mini.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_mini.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_mini.setText(" -");
        jLabel_mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseExited(evt);
            }
        });

        jLabel_exit.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_exit.setText(" x");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseExited(evt);
            }
        });

        tableDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Full name", "Address", "Phone", "Gender", "Plate Num", "Brand"
            }
        ));
        tableDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDriverMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDriver);

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Info");

        jlName1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlName1.setText("Full name");

        tfNameD.setEditable(false);
        tfNameD.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfNameD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNameDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNameDFocusLost(evt);
            }
        });

        jlAdd1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlAdd1.setText("Address");

        tfAddD.setEditable(false);
        tfAddD.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfAddD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAddDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAddDFocusLost(evt);
            }
        });

        jlPhone1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlPhone1.setText("Phone #");

        tfPhoneD.setEditable(false);
        tfPhoneD.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfPhoneD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPhoneDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPhoneDFocusLost(evt);
            }
        });
        tfPhoneD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPhoneDKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("Available Drivers");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setText("Welcome To Book Cab");

        jlPlate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlPlate.setText("Plate Number");

        tfPlate.setEditable(false);
        tfPlate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfPlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPlateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPlateFocusLost(evt);
            }
        });

        tfBrand.setEditable(false);
        tfBrand.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfBrand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBrandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBrandFocusLost(evt);
            }
        });

        jlBrand.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlBrand.setText("Car Brand");

        jlGender.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlGender.setText("Gender");

        tfGender.setEditable(false);
        tfGender.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfGender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfGenderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfGenderFocusLost(evt);
            }
        });

        btnProceed.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnProceed.setText("Proceed to Payment");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel_mini))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlName1)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfAddD, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfNameD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlAdd1)
                                    .addComponent(tfPhoneD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlPhone1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlBrand)
                                    .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlGender)
                                    .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlPlate)
                                    .addComponent(tfPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_exit, jLabel_mini});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mini)
                    .addComponent(jLabel_exit))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNameD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlAdd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAddD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlPlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlPhone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPhoneD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnProceed)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneFocusGained

        jlPhone.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_tfPhoneFocusGained

    private void tfPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneFocusLost

        jlPhone.setForeground(Color.black);

    }//GEN-LAST:event_tfPhoneFocusLost

    private void tfPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPhoneKeyTyped
        //number only

        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_tfPhoneKeyTyped

    private void tfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusGained

        jlName.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_tfNameFocusGained

    private void tfNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusLost

        jlName.setForeground(Color.black);

    }//GEN-LAST:event_tfNameFocusLost

    private void tfAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddFocusGained

        jlAdd.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_tfAddFocusGained

    private void tfAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddFocusLost

        jlAdd.setForeground(Color.black);

    }//GEN-LAST:event_tfAddFocusLost

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        
        
        
    }//GEN-LAST:event_tfNameActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        
        tfName.setEditable(true);
        tfAdd.setEditable(true);
        tfPhone.setEditable(true); 
        //tfID.setEditable(true);
     
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Confirm to Save", "Update", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            
        String fname = tfName.getText();
        String address = tfAdd.getText();
        String phone = tfPhone.getText();
        String id = tfID.getText();

        if(verifyFields()) {


                    PreparedStatement ps;
                    ResultSet rs;
                    String registerUserQuery = "UPDATE `user` SET `full_name` = ?, `address` = ?, `phone` = ? WHERE `id` = ?";

                    try {
                        ps = MyConnect.getConnection().prepareStatement(registerUserQuery);
                        ps.setString(1, fname);
                        ps.setString(2, address);
                        ps.setString(3, phone);
                        ps.setString(4, id);
                        
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Your Booker Account Has been Updated");
                    } catch (SQLException ex) {
                        Logger.getLogger(registerBooker.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        
        tfName.setEditable(false);
        tfAdd.setEditable(false);
        tfPhone.setEditable(false); 
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jLabel_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_miniMouseClicked

    private void jLabel_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_miniMouseEntered

    private void jLabel_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_miniMouseExited

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jLabel_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_exitMouseEntered

    private void jLabel_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_exitMouseExited

    private void tfNameDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameDFocusGained

        jlName1.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfNameDFocusGained

    private void tfNameDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameDFocusLost

        jlName1.setForeground(Color.black);
    }//GEN-LAST:event_tfNameDFocusLost

    private void tfAddDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddDFocusGained

        jlAdd1.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfAddDFocusGained

    private void tfAddDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddDFocusLost

        jlAdd1.setForeground(Color.black);
    }//GEN-LAST:event_tfAddDFocusLost

    private void tfPhoneDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneDFocusGained

        jlPhone1.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfPhoneDFocusGained

    private void tfPhoneDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneDFocusLost

        jlPhone1.setForeground(Color.black);
    }//GEN-LAST:event_tfPhoneDFocusLost

    private void tfPhoneDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPhoneDKeyTyped
        //number only

        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tfPhoneDKeyTyped

    private void tfPlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPlateFocusGained

        jlPlate.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_tfPlateFocusGained

    private void tfPlateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPlateFocusLost

        jlPlate.setForeground(Color.black);

    }//GEN-LAST:event_tfPlateFocusLost

    private void tfBrandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBrandFocusGained

        jlBrand.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_tfBrandFocusGained

    private void tfBrandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBrandFocusLost

        jlBrand.setForeground(Color.black);

    }//GEN-LAST:event_tfBrandFocusLost

    private void tfGenderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfGenderFocusGained
        jlGender.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfGenderFocusGained

    private void tfGenderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfGenderFocusLost
        jlGender.setForeground(Color.black);
    }//GEN-LAST:event_tfGenderFocusLost

    private void tfIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDFocusGained

    private void tfIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDFocusLost

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Confirm to Sign Out", "Sign Out", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            UserLogin u = new UserLogin();
            u.setVisible(true);
            u.pack();
            u.setLocationRelativeTo(null);
            
            this.dispose();
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void tableDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDriverMouseClicked
        
        DefaultTableModel model = (DefaultTableModel)tableDriver.getModel();
        int SelectedRows = tableDriver.getSelectedRow();
        
        tfNameD.setText(model.getValueAt(SelectedRows, 0).toString());
        tfAddD.setText(model.getValueAt(SelectedRows, 1).toString());
        tfPhoneD.setText(model.getValueAt(SelectedRows, 2).toString());
        tfGender.setText(model.getValueAt(SelectedRows, 3).toString());
        tfPlate.setText(model.getValueAt(SelectedRows, 4).toString());
        tfBrand.setText(model.getValueAt(SelectedRows, 5).toString());
        
    }//GEN-LAST:event_tableDriverMouseClicked

    private void jlDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDeleteMouseEntered
        
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204,102,0));
        jlDelete.setBorder(label_border);
        jlDelete.setForeground(new Color(204,102,0));
        
    }//GEN-LAST:event_jlDeleteMouseEntered

    private void jlDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDeleteMouseExited
        
        jlDelete.setBorder(null);
        jlDelete.setForeground(Color.black);
    }//GEN-LAST:event_jlDeleteMouseExited

    private void jlDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDeleteMouseClicked
        
        String id = tfID.getText();
        
        if(JOptionPane.showConfirmDialog(null, "Confirm to Delete", "Delete Account", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            try {
                PreparedStatement ps = MyConnect.getConnection().prepareStatement("DELETE FROM `user` WHERE `id` = ?");
                ps.setString(1, id);


                int k = ps.executeUpdate();

                if(k==1){
                    JOptionPane.showMessageDialog(null, "Your Booker Account Has been Deleted");
                    this.dispose();
                    UserLogin l = new UserLogin();
                    l.setVisible(true);
                    l.pack();
                    l.setLocationRelativeTo(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Your Record Failed to Delete");
                }

            } catch (SQLException ex) {
                Logger.getLogger(registerBooker.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_jlDeleteMouseClicked

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
  
                Payment p = new Payment();
                p.setVisible(true);
                p.pack();
                p.setLocationRelativeTo(null);

                this.dispose();
                 
    }//GEN-LAST:event_btnProceedActionPerformed
    
    
    public boolean verifyFields() {
        
        String fname = tfName.getText();
        String phone = tfPhone.getText();
        String address = tfAdd.getText();
        
        //check empty fields
        if (fname.trim().equals("") || address.trim().equals("") || phone.trim().equals("")) {
            
            JOptionPane.showMessageDialog(null, "One or More Fields Are Empty", "Empty Fields", 2);
            return  false;
        }
        
        //succesfull
        else {
            return true;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Booker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Booker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Booker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Booker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Booker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnProceed;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JLabel cabIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_mini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAdd;
    private javax.swing.JLabel jlAdd1;
    private javax.swing.JLabel jlBrand;
    private javax.swing.JLabel jlDelete;
    private javax.swing.JLabel jlGender;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlName1;
    private javax.swing.JLabel jlName2;
    private javax.swing.JLabel jlPhone;
    private javax.swing.JLabel jlPhone1;
    private javax.swing.JLabel jlPlate;
    private javax.swing.JLabel jluserIcon;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTable tableDriver;
    public static javax.swing.JTextField tfAdd;
    private javax.swing.JTextField tfAddD;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfGender;
    public static javax.swing.JTextField tfID;
    public static javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNameD;
    public static javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfPhoneD;
    private javax.swing.JTextField tfPlate;
    // End of variables declaration//GEN-END:variables
}
