/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bookcab;

import java.awt.Color;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author kriz
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        billHeader();
        
        this.setLocationRelativeTo(null);
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_exit.setBorder(label_border);
      
    }
    
    private void billHeader() {
        taReceipt.setText("===================================="+"\n"+"\t"+"       BookCab"+"\n"+"                 Contact Number: 0912345678"+"\n"
        +"         Address: Secret, Nasa Philippines, Earth"+"\n"+"                 UNIVERSITY OF MINDANAO"+"\n" 
                +"===================================="+"\n"
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jlName = new javax.swing.JLabel();
        tfAmount = new javax.swing.JTextField();
        jlAmount = new javax.swing.JLabel();
        tfCardN = new javax.swing.JTextField();
        jlCardN = new javax.swing.JLabel();
        btnPayment = new javax.swing.JButton();
        jlSignOut = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taReceipt = new javax.swing.JTextArea();
        lbTitle1 = new javax.swing.JLabel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_mini = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setToolTipText("");

        lbTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 51, 51));
        lbTitle.setText("Payment");

        tfName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNameFocusLost(evt);
            }
        });
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        jlName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlName.setText("Name");

        tfAmount.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAmountFocusLost(evt);
            }
        });
        tfAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAmountActionPerformed(evt);
            }
        });

        jlAmount.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlAmount.setText("Amount");

        tfCardN.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfCardN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCardNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCardNFocusLost(evt);
            }
        });
        tfCardN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCardNActionPerformed(evt);
            }
        });

        jlCardN.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlCardN.setText("Card Number");

        btnPayment.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnPayment.setText("Confirm Payment");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        jlSignOut.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlSignOut.setText("Sign Out");
        jlSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSignOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSignOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSignOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlName)
                            .addComponent(lbTitle)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCardN)
                                    .addComponent(jlAmount)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfCardN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jlSignOut)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbTitle)
                .addGap(18, 18, 18)
                .addComponent(jlName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCardN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCardN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPayment)
                .addGap(18, 18, 18)
                .addComponent(jlSignOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taReceipt.setEditable(false);
        taReceipt.setColumns(20);
        taReceipt.setRows(5);
        jScrollPane1.setViewportView(taReceipt);

        lbTitle1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        lbTitle1.setForeground(new java.awt.Color(51, 51, 51));
        lbTitle1.setText("Receipt");

        jLabel_exit.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_exit.setText(" x");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseExited(evt);
            }
        });

        jLabel_mini.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_mini.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_mini.setText(" -");
        jLabel_mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseExited(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_mini)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(lbTitle1)
                                .addGap(65, 65, 65)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_exit, jLabel_mini});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mini)
                    .addComponent(jLabel_exit))
                .addGap(18, 18, 18)
                .addComponent(lbTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrint)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusGained

        jlName.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_tfNameFocusGained

    private void tfNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusLost

        jlName.setForeground(Color.black);
    }//GEN-LAST:event_tfNameFocusLost

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed

    }//GEN-LAST:event_tfNameActionPerformed

    private void tfAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAmountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAmountFocusGained

    private void tfAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAmountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAmountFocusLost

    private void tfAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAmountActionPerformed

    private void tfCardNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCardNFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCardNFocusGained

    private void tfCardNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCardNFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCardNFocusLost

    private void tfCardNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCardNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCardNActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed

        String fname = tfName.getText();
        String cardNum = tfCardN.getText();
        String amount = tfAmount.getText();
        
        if(verifyFields()) {
            
            if(JOptionPane.showConfirmDialog(null, "Confirm Payment", "Payment", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
                
                PreparedStatement ps;
                ResultSet rs;
                String BookerQuery = "INSERT INTO `payment`(`full_name`, `card_number`, `amount`) VALUES (?,?,?)";
                
                try {
                    
                    ps = MyConnect.getConnection().prepareStatement(BookerQuery);
                    ps.setString(1, fname);
                    ps.setString(2, cardNum);
                    ps.setString(3, amount);
                    
                    if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Payment Confirm, Receipt Created");
                        
                        Date obj = new Date();
                        String date = obj.toString();

                        taReceipt.setText(taReceipt.getText()+"\n"+date+"\n \n");
                        taReceipt.setText(taReceipt.getText()+"Name:"+"\t"+tfName.getText()+"\n");
                        taReceipt.setText(taReceipt.getText()+"Card Number:"+"\t"+tfCardN.getText()+"\n");
                        taReceipt.setText(taReceipt.getText()+"Amount:"+"\t"+tfAmount.getText()+"\n");
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Error! Check Your Information");
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(registerBooker.class.getName()).log(Level.SEVERE, null, ex);
                }  
            } 
        }
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jLabel_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_exitMouseEntered

    private void jLabel_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_exitMouseExited

    private void jLabel_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_miniMouseClicked

    private void jLabel_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_miniMouseEntered

    private void jLabel_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_miniMouseExited

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        
        try {
            taReceipt.print();
        } catch(Exception e) {
            
        }
       
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jlSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSignOutMouseClicked
        
        if(JOptionPane.showConfirmDialog(null, "Confirm Sign Out", "Sign Out", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            
            UserLogin l = new UserLogin();
            l.setVisible(true);
            l.pack();
            l.setLocationRelativeTo(null);
            
            this.dispose();
        }

    }//GEN-LAST:event_jlSignOutMouseClicked

    private void jlSignOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSignOutMouseEntered

        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204,102,0));
        jlSignOut.setBorder(label_border);
        jlSignOut.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_jlSignOutMouseEntered

    private void jlSignOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSignOutMouseExited

        jlSignOut.setBorder(null);
        jlSignOut.setForeground(Color.black);
    }//GEN-LAST:event_jlSignOutMouseExited

    
    public boolean verifyFields() {
        
        String fname = tfName.getText();
        String cardNum = tfCardN.getText();
        String amount = tfAmount.getText();
        
        //check empty fields
        if (fname.trim().equals("") || cardNum.trim(). equals("") || amount.trim().equals("")) {
            
            JOptionPane.showMessageDialog(null, "One or More Fields Are Empty", "Empty Fields", 2);
            return  false;
        }
        else {
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_mini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAmount;
    private javax.swing.JLabel jlCardN;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlSignOut;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTitle1;
    private javax.swing.JTextArea taReceipt;
    public static javax.swing.JTextField tfAmount;
    public static javax.swing.JTextField tfCardN;
    public static javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
