/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bookcab;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author kriz
 */
public class registerDriver extends javax.swing.JFrame {

    /**
     * Creates new form registerDriver
     */
    public registerDriver() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        //create border for minimize and exit labels
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_exit.setBorder(label_border);
        
        //button group
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbMale);
        bg.add(rbFemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMain = new javax.swing.JPanel();
        jpInfo = new javax.swing.JPanel();
        jlUser = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        jlPass = new javax.swing.JLabel();
        jfPass = new javax.swing.JPasswordField();
        jlName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jlAdd = new javax.swing.JLabel();
        tfAdd = new javax.swing.JTextField();
        jlPhone = new javax.swing.JLabel();
        tfPhone = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jlConPass = new javax.swing.JLabel();
        jfConPass = new javax.swing.JPasswordField();
        jlGender = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jlPlate = new javax.swing.JLabel();
        tfPlate = new javax.swing.JTextField();
        tfBrand = new javax.swing.JTextField();
        jlBrand = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jpTitle = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jLabel_mini = new javax.swing.JLabel();
        jLabel_exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpMain.setBackground(new java.awt.Color(204, 204, 0));
        jpMain.setForeground(new java.awt.Color(255, 255, 255));

        jlUser.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlUser.setText("Username");

        tfUser.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUserFocusLost(evt);
            }
        });
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });

        jlPass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlPass.setText("Password");

        jfPass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jfPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfPassFocusLost(evt);
            }
        });

        jlName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlName.setText("Full name");

        tfName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNameFocusLost(evt);
            }
        });

        jlAdd.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlAdd.setText("Address");

        tfAdd.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAddFocusLost(evt);
            }
        });

        jlPhone.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlPhone.setText("Phone #");

        tfPhone.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPhoneFocusLost(evt);
            }
        });
        tfPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPhoneKeyTyped(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(204, 102, 0));
        btnRegister.setText("Register");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jlConPass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlConPass.setText("Confirm Password");

        jfConPass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jfConPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfConPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfConPassFocusLost(evt);
            }
        });

        jlGender.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlGender.setText("Gender");

        rbMale.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        rbMale.setSelected(true);
        rbMale.setText("Male");

        rbFemale.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        rbFemale.setText("Female");

        jlPlate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlPlate.setText("Plate Number");

        tfPlate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfPlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPlateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPlateFocusLost(evt);
            }
        });

        tfBrand.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfBrand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBrandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBrandFocusLost(evt);
            }
        });

        jlBrand.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlBrand.setText("Car Brand");

        btnBack.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnBack.setText("Back to Login");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpInfoLayout = new javax.swing.GroupLayout(jpInfo);
        jpInfo.setLayout(jpInfoLayout);
        jpInfoLayout.setHorizontalGroup(
            jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInfoLayout.createSequentialGroup()
                        .addComponent(jlGender, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFemale))
                    .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpInfoLayout.createSequentialGroup()
                            .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlConPass)
                                .addComponent(tfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(jfPass)
                                .addComponent(jlPass)
                                .addComponent(jlName)
                                .addComponent(jlUser)
                                .addComponent(jfConPass)
                                .addComponent(tfName))
                            .addGap(18, 18, 18)
                            .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlPlate)
                                .addComponent(jlBrand)
                                .addComponent(tfBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(tfPlate)
                                .addComponent(tfPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(jlPhone)
                                .addComponent(jlAdd)
                                .addComponent(tfAdd)))
                        .addGroup(jpInfoLayout.createSequentialGroup()
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpInfoLayout.setVerticalGroup(
            jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpInfoLayout.createSequentialGroup()
                        .addComponent(jlName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoLayout.createSequentialGroup()
                        .addComponent(jlPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpInfoLayout.createSequentialGroup()
                        .addComponent(jlPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlConPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfConPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoLayout.createSequentialGroup()
                        .addComponent(jlPlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGender)
                    .addComponent(rbFemale)
                    .addComponent(rbMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnBack))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jlTitle.setBackground(new java.awt.Color(153, 51, 0));
        jlTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(102, 0, 0));
        jlTitle.setText("Driver");

        jLabel_mini.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_mini.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_mini.setText(" -");
        jLabel_mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseExited(evt);
            }
        });

        jLabel_exit.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_exit.setText(" x");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpTitleLayout = new javax.swing.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addContainerGap(561, Short.MAX_VALUE)
                .addComponent(jLabel_mini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jlTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpTitleLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_exit, jLabel_mini});

        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mini)
                    .addComponent(jLabel_exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTitle)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserFocusGained

        jlUser.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_tfUserFocusGained

    private void tfUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserFocusLost

        jlUser.setForeground(Color.black);

    }//GEN-LAST:event_tfUserFocusLost

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void jfPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfPassFocusGained

        jlPass.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_jfPassFocusGained

    private void jfPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfPassFocusLost

        jlPass.setForeground(Color.black);

    }//GEN-LAST:event_jfPassFocusLost

    private void tfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusGained

        jlName.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_tfNameFocusGained

    private void tfNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusLost

        jlName.setForeground(Color.black);

    }//GEN-LAST:event_tfNameFocusLost

    private void tfAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddFocusGained

        jlAdd.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_tfAddFocusGained

    private void tfAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddFocusLost

        jlAdd.setForeground(Color.black);

    }//GEN-LAST:event_tfAddFocusLost

    private void tfPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneFocusGained

        jlPhone.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_tfPhoneFocusGained

    private void tfPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneFocusLost

        jlPhone.setForeground(Color.black);

    }//GEN-LAST:event_tfPhoneFocusLost

    private void tfPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPhoneKeyTyped
        //number only

        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_tfPhoneKeyTyped

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Confirm if you want to Register into Driver", "Driver Register", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            
            String fname = tfName.getText();
            String username = tfUser.getText();
            String pass = String.valueOf(jfPass.getPassword());
            //String conPass = String.valueOf(jfConPass.getPassword());
            String address = tfAdd.getText();
            String phone = tfPhone.getText();
            String gender = "Male";
            String platenumber = tfPlate.getText();
            String cartype = tfBrand.getText();

            if(rbFemale.isSelected()) {
                gender = "Female";
            }

            if(verifyFields()) {

                if(!checkUser(username)) {

                    PreparedStatement ps;
                    ResultSet rs;
                    String registerUserQuery = "INSERT INTO `driver`(`full_name`, `username`, `password`, `address`, `phone`, `gender`, `plateNumber`, `carType`) VALUES (?,?,?,?,?,?,?,?)";

                    try {
                        ps = MyConnect.getConnection().prepareStatement(registerUserQuery);
                        ps.setString(1, fname);
                        ps.setString(2, username);
                        ps.setString(3, pass);
                        ps.setString(4, address);
                        ps.setString(5, phone);
                        ps.setString(6, gender);
                        ps.setString(7, platenumber);
                        ps.setString(8, cartype);


                        try {

                            //ps.setNull(7, java.sql.Types.NULL);

                            if (ps.executeUpdate() != 0) {
                                JOptionPane.showMessageDialog(null, "Your Driver Account Has been Created");

                            } else {
                                JOptionPane.showMessageDialog(null, "Error! Check Your Information");
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(registerBooker.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(registerBooker.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
            
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jfConPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfConPassFocusGained

        jlConPass.setForeground(new Color(204,102,0));

    }//GEN-LAST:event_jfConPassFocusGained

    private void jfConPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfConPassFocusLost

        jlConPass.setForeground(Color.black);

    }//GEN-LAST:event_jfConPassFocusLost

    private void jLabel_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_miniMouseClicked

    private void jLabel_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_miniMouseEntered

    private void jLabel_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_miniMouseExited

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jLabel_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_exitMouseEntered

    private void jLabel_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_exitMouseExited

    private void tfPlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPlateFocusGained
        
        jlPlate.setForeground(new Color(204,102,0));
        
    }//GEN-LAST:event_tfPlateFocusGained

    private void tfPlateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPlateFocusLost
        
        jlPlate.setForeground(Color.black);
        
    }//GEN-LAST:event_tfPlateFocusLost

    private void tfBrandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBrandFocusGained
        
        jlBrand.setForeground(new Color(204,102,0));
        
    }//GEN-LAST:event_tfBrandFocusGained

    private void tfBrandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBrandFocusLost
        
        jlBrand.setForeground(Color.black);
        
    }//GEN-LAST:event_tfBrandFocusLost

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        UserLogin login = new UserLogin();
        login.pack();
        login.setVisible(true);
        login.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    //funtion for empty fields 
    public boolean verifyFields() {
        
        String uname = tfUser.getText();
        String fname = tfName.getText();
        String phone = tfPhone.getText();
        String address = tfAdd.getText();
        String plate = tfPlate.getText();
        String brand = tfBrand.getText();
        String pass = String.valueOf(jfPass.getPassword());
        String ConPass = String.valueOf(jfConPass.getPassword());
        
        //check empty fields
        if (fname.trim().equals("") || uname.trim().equals("") || address.trim().equals("") || plate.trim().equals("")
                || brand.trim().equals("")|| phone.trim().equals("")
                || pass.trim(). equals("") || ConPass.trim().equals("")) {
            
            JOptionPane.showMessageDialog(null, "One or More Fields Are Empty", "Empty Fields", 2);
            return  false;
        }
        //check password not match 
        else if (!pass.equals(ConPass)) {
            
            JOptionPane.showMessageDialog(null, "Password Doesn't Match", "Confirm Password", 2);
            return  false;
        }   
        //succesfull
        else {
            return true;
        }
    }
    
    // funtion already exists in the database
    public boolean checkUser(String username) {
        
        PreparedStatement st;
        ResultSet rs;
        boolean user_exist = false;
        
        String query = "SELECT * FROM `driver` WHERE `username` = ? ";
        
        try {
            
            st = MyConnect.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if(rs.next()) {
                user_exist = true;
                JOptionPane.showMessageDialog(null, "This Username is Already Taken,\n Chooose Another One.", "Username Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(registerBooker.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return user_exist;
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_mini;
    private javax.swing.JPasswordField jfConPass;
    private javax.swing.JPasswordField jfPass;
    private javax.swing.JLabel jlAdd;
    private javax.swing.JLabel jlBrand;
    private javax.swing.JLabel jlConPass;
    private javax.swing.JLabel jlGender;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlPass;
    private javax.swing.JLabel jlPhone;
    private javax.swing.JLabel jlPlate;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlUser;
    private javax.swing.JPanel jpInfo;
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jpTitle;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField tfAdd;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfPlate;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
