package com.mycompany.bookcab;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author kriz
 */
public class UserLogin extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();

        //center components 
        this.setLocationRelativeTo(null);

        //create border for minimize and exit labels
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_exit.setBorder(label_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        plBackground = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        lbCCEicon = new javax.swing.JLabel();
        lbUMicon = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        lbPass = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jPassf = new javax.swing.JPasswordField();
        jLabel_mini = new javax.swing.JLabel();
        jLabel_exit = new javax.swing.JLabel();
        cabIcon = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        plBackground.setBackground(new java.awt.Color(204, 204, 0));

        logoPanel.setBackground(new java.awt.Color(153, 51, 0));

        lbCCEicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kriz\\OneDrive - umindanao.edu.ph\\Documents\\IconProject\\CCE-copy.png")); // NOI18N

        lbUMicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kriz\\OneDrive - umindanao.edu.ph\\Documents\\IconProject\\University_of_Mindanao_Logo.png")); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCCEicon)
                    .addComponent(lbUMicon))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbCCEicon)
                .addGap(35, 35, 35)
                .addComponent(lbUMicon)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        lbTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 51, 51));
        lbTitle.setText("BooK");

        lbUser.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lbUser.setForeground(new java.awt.Color(51, 51, 51));
        lbUser.setText("Username");

        tfUser.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfUser.setForeground(new java.awt.Color(153, 153, 153));
        tfUser.setText("gwapo ko");
        tfUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUserFocusLost(evt);
            }
        });
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });

        lbPass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lbPass.setForeground(new java.awt.Color(51, 51, 51));
        lbPass.setText("Password");

        btnLogin.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(204, 102, 0));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(204, 102, 0));
        btnRegister.setText("Register");
        btnRegister.setActionCommand("register");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jPassf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPassf.setForeground(new java.awt.Color(153, 153, 153));
        jPassf.setText("password");
        jPassf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPassfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPassfFocusLost(evt);
            }
        });
        jPassf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassfActionPerformed(evt);
            }
        });

        jLabel_mini.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_mini.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_mini.setText(" -");
        jLabel_mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseExited(evt);
            }
        });

        jLabel_exit.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_exit.setText(" x");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseExited(evt);
            }
        });

        cabIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kriz\\OneDrive - umindanao.edu.ph\\Documents\\IconProject\\cab.png")); // NOI18N

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_mini)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(lbTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cabIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(loginPanelLayout.createSequentialGroup()
                                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfUser)
                                .addComponent(lbUser)
                                .addComponent(lbPass)
                                .addComponent(jPassf, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );

        loginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_exit, jLabel_mini});

        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mini)
                    .addComponent(jLabel_exit))
                .addGap(55, 55, 55)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cabIcon)
                    .addComponent(lbTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister)
                    .addComponent(btnLogin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout plBackgroundLayout = new javax.swing.GroupLayout(plBackground);
        plBackground.setLayout(plBackgroundLayout);
        plBackgroundLayout.setHorizontalGroup(
            plBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plBackgroundLayout.setVerticalGroup(
            plBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        PreparedStatement stb, std;
        ResultSet rsb, rsd;
        
        //get the username & password
        String username = tfUser.getText();
        String password = String.valueOf(jPassf.getPassword());
        
        //create a quary
        String bookerQuery = "SELECT * FROM `user` WHERE `username` = ? AND `password` = ?";
        String driverQuery = "SELECT * FROM `driver` WHERE `username` = ? AND `password` = ?";
        
        //show empty message 
        
        if(username.trim().equals("gwapo ko")) {
            JOptionPane.showMessageDialog(null, "Enter Username", "Empty Username", 2);
        } else if(password.trim().equals("password")) {
            JOptionPane.showMessageDialog(null, "Enter Password", "Empty Password", 2);
        }   else {
            
            try {
            
            //variable for booker 
            stb = MyConnect.getConnection().prepareStatement(bookerQuery);
            
            stb.setString(1, username);
            stb.setString(2, password);
            
            rsb = stb.executeQuery();
            
            //variable for driver
            std = MyConnect.getConnection().prepareStatement(driverQuery);
            
            std.setString(1, username);
            std.setString(2, password);
            
            rsd = std.executeQuery();
            
            if(rsb.next()) {
                

                //show a new form
                Menu_Booker menubooker = new Menu_Booker();
                menubooker.setVisible(true);
                menubooker.pack();
                menubooker.setLocationRelativeTo(null);
                
                Menu_Booker.tfID.setText(rsb.getString(String.valueOf("id")));
                Menu_Booker.tfName.setText(rsb.getString(String.valueOf("full_name")));
                Menu_Booker.tfAdd.setText(rsb.getString(String.valueOf("address")));
                Menu_Booker.tfPhone.setText(rsb.getString(String.valueOf("phone")));
                
                this.dispose();
                
             
            } else if(rsd.next()) {
                

                //show a new form
                Menu_Driver menudriver = new Menu_Driver();
                menudriver.setVisible(true);
                menudriver.pack();
                menudriver.setLocationRelativeTo(null);
                
                Menu_Driver.tfID.setText(rsd.getString(String.valueOf("id")));
                Menu_Driver.tfName.setText(rsd.getString(String.valueOf("full_name")));
                Menu_Driver.tfAdd.setText(rsd.getString(String.valueOf("address")));
                Menu_Driver.tfPhone.setText(rsd.getString(String.valueOf("phone")));
                Menu_Driver.tfPlate.setText(rsd.getString(String.valueOf("plateNumber")));
                Menu_Driver.tfBrand.setText(rsd.getString(String.valueOf("carType")));
                
                this.dispose();
               
            } else {
                //error message
                JOptionPane.showMessageDialog(null, "Invalid Username or Password", "Login Error", 2);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void jPassfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassfActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        chooseForm cf = new chooseForm();
        cf.pack();
        cf.setVisible(true);
        cf.setLocationRelativeTo(null);

        this.dispose();

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jLabel_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.white);

    }//GEN-LAST:event_jLabel_miniMouseEntered

    private void jLabel_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_mini.setBorder(label_border);
        jLabel_mini.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_miniMouseExited

    private void jLabel_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.white);

    }//GEN-LAST:event_jLabel_exitMouseEntered

    private void jLabel_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_exit.setBorder(label_border);
        jLabel_exit.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_exitMouseExited

    private void tfUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserFocusGained

        //clear textfield
        if (tfUser.getText().trim().toLowerCase().equals("gwapo ko")) {

            tfUser.setText("");
            tfUser.setForeground(Color.black);
        }

        lbUser.setForeground(new Color(204, 102, 0));
    }//GEN-LAST:event_tfUserFocusGained

    private void tfUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserFocusLost

        if (tfUser.getText().trim().equals("") || tfUser.getText().trim().toLowerCase().equals("gwapo ko")) {

            tfUser.setText("gwapo ko");
            tfUser.setForeground(new Color(153, 153, 153));

        }

        lbUser.setForeground(Color.black);
    }//GEN-LAST:event_tfUserFocusLost

    private void jPassfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassfFocusGained

        //clear textfield
        String pass = String.valueOf(jPassf.getPassword());

        if (pass.trim().toLowerCase().equals("password")) {

            jPassf.setText("");
            jPassf.setForeground(Color.black);
        }

        lbPass.setForeground(new Color(204, 102, 0));


    }//GEN-LAST:event_jPassfFocusGained

    private void jPassfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassfFocusLost

        String pass = String.valueOf(jPassf.getPassword());

        if (pass.trim().equals("") || pass.trim().toLowerCase().equals("password")) {

            jPassf.setText("password");
            jPassf.setForeground(new Color(153, 153, 153));

        }

        lbPass.setForeground(Color.black);

    }//GEN-LAST:event_jPassfFocusLost

    private void jLabel_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseClicked

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabel_miniMouseClicked

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabel_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel cabIcon;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_mini;
    public static javax.swing.JPasswordField jPassf;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lbCCEicon;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUMicon;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel plBackground;
    public static javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
